import type { MediaItem } from "@/lib/types";

export const mockMediaItems: MediaItem[] = [
  {
    id: "1",
    name: "Holiday Photos.zip",
    type: "archive",
    url: "https://placehold.co/800x600.png?text=Holiday+Photos+Preview",
    thumbnailUrl: "https://placehold.co/200x150.png",
    dataAiHint: "archive folder",
    timestamp: new Date("2023-08-15T10:30:00Z").getTime(),
    tags: ["vacation", "summer", "archive"],
    size: "15.3 MB",
  },
  {
    id: "2",
    name: "Project Presentation.mp4",
    type: "video",
    url: "https://placehold.co/800x600.png?text=Project+Presentation+Preview",
    thumbnailUrl: "https://placehold.co/200x150.png",
    dataAiHint: "video play",
    timestamp: new Date("2023-09-02T14:00:00Z").getTime(),
    tags: ["work", "project", "business"],
    size: "120.5 MB",
  },
  {
    id: "3",
    name: "Annual Report.pdf",
    type: "document",
    url: "https://placehold.co/800x600.png?text=Annual+Report+Preview",
    thumbnailUrl: "https://placehold.co/200x150.png",
    dataAiHint: "document paper",
    timestamp: new Date("2023-07-20T09:15:00Z").getTime(),
    tags: ["finance", "report", "yearly"],
    size: "2.1 MB",
  },
  {
    id: "4",
    name: "Beach Sunset.jpg",
    type: "image",
    url: "https://placehold.co/800x600.png?text=Beach+Sunset+Preview",
    thumbnailUrl: "https://placehold.co/200x150.png",
    dataAiHint: "beach sunset",
    timestamp: new Date("2023-08-25T18:45:00Z").getTime(),
    tags: ["nature", "travel", "scenery"],
    size: "3.5 MB",
  },
  {
    id: "5",
    name: "Podcast Episode 5.mp3",
    type: "audio",
    url: "https://placehold.co/800x600.png?text=Podcast+Episode+Preview",
    thumbnailUrl: "https://placehold.co/200x150.png",
    dataAiHint: "audio waveform",
    timestamp: new Date("2023-09-10T11:00:00Z").getTime(),
    tags: ["podcast", "interview", "tech"],
    size: "25.8 MB",
  },
  {
    id: "6",
    name: "Software Manual.docx",
    type: "document",
    url: "https://placehold.co/800x600.png?text=Software+Manual+Preview",
    thumbnailUrl: "https://placehold.co/200x150.png",
    dataAiHint: "document manual",
    timestamp: new Date("2023-06-01T16:20:00Z").getTime(),
    tags: ["software", "guide", "documentation"],
    size: "0.8 MB",
  },
  {
    id: "7",
    name: "Company Logo.png",
    type: "image",
    url: "https://placehold.co/800x600.png?text=Company+Logo+Preview",
    thumbnailUrl: "https://placehold.co/200x150.png",
    dataAiHint: "logo design",
    timestamp: new Date("2023-05-10T12:00:00Z").getTime(),
    tags: ["branding", "design", "asset"],
    size: "0.2 MB",
  },
  {
    id: "8",
    name: "Client Meeting Notes.txt",
    type: "document",
    url: "https://placehold.co/800x600.png?text=Meeting+Notes+Preview",
    thumbnailUrl: "https://placehold.co/200x150.png",
    dataAiHint: "notes text",
    timestamp: new Date("2023-09-05T10:00:00Z").getTime(),
    tags: ["meeting", "notes", "client"],
    size: "0.1 MB",
  },
];
